services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: react-client
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./:/app
      - /app/node_modules